default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: narek
  host: localhost
  port: 5432

development:
  <<: *default
  database: ruby_on_rails_to_do_development

test:
  <<: *default
  database: ruby_on_rails_to_do_test
